### ISSUE TITLE
Cant open the app

### ISSUE THREAD

**Issue by aldesrahim** [medhachaitanya/Whatsapp-Web-Lock-Windows-UWP#1]
Hello, this project was great, but after installing certificate then the WhatsApp, app keep closing on start

**Comment by medhachaitanya** [comment]
Oh I see. I will check and let you know.

**Comment by medhachaitanya** [comment]
@aldesrahim I tried installing and running the app on multiple systems and it seems to be working fine. 
Could you please share your OS version so that I can look into more detail ?

**Comment by aldesrahim** [comment]
![image](https://user-images.githubusercontent.com/37100012/94095827-ba03c400-fe4c-11ea-8359-1d2b1fe44f4e.png)
i use this windows version: [Pure OS](https://www.teamos-hkrg.com/threads/windows-pure-10-pro-x64-teamos.84143/)

**Comment by medhachaitanya** [comment]
I have updated the app and the certificate. Please try again. Thank you.
