### ISSUE TITLE
App can't be installed

### ISSUE THREAD

**Issue by Ujimondal** [medhachaitanya/Whatsapp-Web-Lock-Windows-UWP#4]
I am on Windows 11 with version 22H2. I installed the certificate that you gave in trusted people, but then can't install the app. Attaching a screenshot url for your reference. Hope to hear from you soon.[https://drive.google.com/file/d/12MKiE8L6fB3llJQv-wQFbjPeKciRjnCg/view?usp=sharing](url)

**Comment by Ujimondal** [comment]
https://drive.google.com/file/d/12MKiE8L6fB3llJQv-wQFbjPeKciRjnCg/view?usp=sharing

**Comment by medhachaitanya** [comment]
Updated the application & the app certificate. Please try again and reopen the issue if it still persist.
